services:
  db:
    image: postgres:15.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    logging:
      options:
        max-file: "1"
        max-size: "5m"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && tail -f /etc/hostname"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    logging:
      options:
        max-file: "1"
        max-size: "2m"
    depends_on:
      - db